language: objective-c
osx_image: xcode7
before_install:
- gem install fir-cli --no-ri --no-rdoc
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/HbridADHoc1.mobileprovision.enc
  -d -a -out scripts/profile/HbridADHoc1.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- "./scripts/add-key.sh"
script:
- xctool -workspace HybridDemo.xcworkspace -scheme HybridDemo -sdk iphoneos -configuration Release OBJROOT=build SYMROOT=build ONLY_ACTIVE_ARCH=NO
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
env:
  global:
  - APP_NAME="HybridDemo"
  - 'DEVELOPER_NAME="iPhone Distribution: qi ming dong"'
  - PROFILE_NAME="HbridADHoc1"
  - secure: WksyubO79HdaQ5lB+UA4MvRCt9nYYLm0NIO7lLjUQbmJehAHeFZolPgvcKNTIQ4TJODf7JH6Zq2aVgoyGbVgaA1FKMo0Zyu7GbDoxGVZmOFKLy1V3FxR2qLZlQhj7YdYmV+bwZqVvaEXOvSewAwGSOVk4ECI8Z6qycEi8lPkamPi9bKVlp/2Os0ln78JN69KxtR0cPmPoA6YQWtO0Odjryja3B3mU28ukfPcShRs479MFfsEDFlpfb33Di09WUqhJ5+Ft2IIXu28wO/w2fMl6zsPSHMmFg8FEpOgnAQ4a2RMesAdgbSW8E6+N1wsr5V2QLiDj7v0FOJ+9jwvgRvOf532/Z9TONnnJh/5UUfyXmxtvsQ1BaLEma16y5Oc5D8+FkhJpWGcdiIC629e36xLihSmT/elbpKyEyRIwPyxRVXEf5/gB6OGOIsre/QYlAqJkdEtTVZwAHk3VIP0lEYLrszK67hQcf2GNWYApSCTAPFRcYp9gOzj83+jqhd1e6y7NpXeOkfNFamJ6ZGr6FhvJqeX5enqdHyAITaDyqvTH0Ngwiq2J6F6sZ5XcMsz311aW+7tQjo2+tN7koG+aZ5Z5G1I2v+/gvLqkcoyKlaOUjy4L4NNfho3VPbuAvN8ApxZfT8EQ0hQ31g2rS6h2bwRvwgurtmS6Tm05TS4HWBiuH4=
  - secure: ZtlX9KaslO+uS58jNfu8C/PQD/xkZzWDZ6rfnfb5rtam9Qacd7crI1cVh9E5EMZ9RwoIE0MOekmwA4GQVMKwW+4LyF6gA7l8Kdl98HQwUlO5I8RfwaWnmd1Zux7B+/oS5rSw0qVN+gN737exANT2Nf8YKiapXNlZYlH8P8mO4FIpdSd6tNKBdRHjaaijCXNzHMm4Lz1Unb/4HuPgpTCSIOGPtTBZF/ETDhv8mjUvDkdT13W+YaP7gzUm456IFx39aAPO/0tICYdvKDW8O0uqMx0GW2b0puwU5NUOBY1KVyF+S2fF6x1WtFcJdYbJoi+9oCd1hnO8C+uK+FpuPGvmz6hgUMRvpLlRhQ93e4EFHRkDdPj+IL8feqnOYJWhE1ho2NmMPl8fQcPRt6zn3Hbkgul0TLsGE47NTEm7wfcTeTLWpu0CM9LJfXbjtwqIHL5r8sGE/n6H4J2BaqlKpuDcKvArEiBu7u7eC7raj+dFlUfA/Jcwl0rRPHahItL3gldYwicneqSfhU34ZOy2Lz+VNHvzbnpeslwHmaADgwaAGQgfINR80E3LAZOKiesKv1ciewEWW+co7P/6cIykvHoynhbjSk4Xw8jSOUJElyyGZGxInJ0sfCn7MpczUP3tvOYm6gqwBQs9hxjbZBgALwtTahqGGNfocvRN6LQ2jY2f/qU=
  - secure: g+zav92nikbZOxrYkNZmKDPYE5fKvj81PG3kn4bvmj9Y6O90i2+ktFuXvI6WBuahlof76zRUP6NxhrRsm+uIfh1oLs9XOcM3/8UaKS5QsHv1JeWLodnEfg7tlTlOu5aD7zJZSjBkaF+gOSf3zsqPixsSGrAvsnJ/Dz6zTTpQW68x2WS/CG5rmdvbAgxQDXxK7BlGTiF6RkxeFpca8REHeMO5ltOlkK6Naz7HUoYT6Us+kkFDn/KLj2c63/H9oPds8MOFZXVuRJZY6bFbosYiOF+V63krCZluOp0r8WQSorT3B9mZVQvi2KWKpy2jSZ92tJoY2Psj0cHBoPuO1V6QOpgYO7GuMCMXiFmEaKSzidXI+Lb+pnPsGkXBuW6RgbuvCHMV5AFbtOc5cYlbgcKxF7vUuz8BPb2TmO9GEbBng1rpJ5QVPy9vVTzj1VeL+NIlKAA+sZuSEQx2J2sldYKCzYQl8r6cYSxrr3XZ3GlPSrJAkbMPCmhBcZwTW6KjeMAf8VI7JwpLk5ULPd1b/hIQFFgG6yc+SE3m3zsCoh7pJ5fjDoyzZXFw4DjCMtp1EQ2X93ZjfVU7HGdXp84re0ce9NBlTkdQx4v1HOZ47UaHQPeC+fwzIUG5d/jsQEtglettHEsDW7ok5nHeF8hklujoc8x7yksg0Ug1pGyeOE+zaBw=
